name: Launchable Demo

on:
  push:
    branches:
      - main

jobs:
  primary-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "adopt"
      - name: Compile
        run: mvn compile
  worker-node-1:
    runs-on: ubuntu-latest
    needs: [ primary-node ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "adopt"
      - name: Test
        run: mvn test

