name: Launchable Demo

on:
  pull_request:
  workflow_dispatch:

jobs:
  primary-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "adopt"
      - name: Compile
        run: mvn compile
  worker-node-1:
    runs-on: ubuntu-latest
    needs: [primary-node]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "adopt"
      - name: Test
        run: mvn test
