name: Launchable Demo Pre-Merge

on:
  push:
    branches:
      - main

env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "adopt"
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Launchable command
        run: pip install --user --upgrade launchable~=1.0
      - name: Launchable verify
        run: launchable verify
      - name: Launchable record build
        run: launchable record build --name ${{ github.run_id }}
      - name: launchable subset
        run: |
          launchable subset --observation --target 50% maven src/test/java > launchable-subset.txt
          cat launchable-subset.txt
      - name: Compile
        run: mvn compile
      - name: Test
        run: mvn test -Dsurefire.includesFile=launchable-subset.txt
      - name: Launchable record tests
        if: always()
        run: launchable record tests maven ./**/target/surefire-reports
